# Generated by Django 3.0.6 on 2020-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('dividend', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
